name: robots-update

on:
  schedule:
    - cron: "0 * * * *"
    
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v4
      - name: Base blocklist generation
        run: |
          mkdir -p ./ip-blocklist
          cd ./ip-blocklit
            curl http://213.165.81.47:5899/ip.txt > $(basename $ip)
          done
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add -A ./ip-blocklist
          git commit -a -m "updated robots"
          git push origin main
